### ISSUE TITLE
pr2 joint calibration

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/snippets#47]
## google groups 情報
https://groups.google.com/g/pr2_users/c/QpReAo30eeA?pli=1

## full system calibration 
https://wiki.ros.org/pr2_calibration/Tutorials/Calibrating%20the%20PR2
urdfの書き換えによってcalibrationをしている. 
https://www.youtube.com/watch?v=TwL4xqBLUdo
動画によるとnonlinear optimizatoinといっているのでfkといて最小二乗法でもしているのだろう
joint calibrationだけしたくて, cameraはskipしたいのだが, それはできる??

## github package
https://github.com/PR2/pr2_calibration/blob/kinetic-devel/pr2_se_calibration_launch/capture_data/pr2_se_exec.py#L142

**Comment by HiroIshida** [comment]
calibration launchのpythonがnoeticでreleaseされてるのに, python2 でかかれている. 
2to3で修正 https://github.com/HiroIshida/calibration/commit/9c433b6d17efa8d29334b8e13bace423efccc263

**Comment by HiroIshida** [comment]
pr2のurdfが読めないというエラーがでてくる
```
Unknown attribute "type" in /robot[@name='pr2']/link[@name='base_laser_link']
Unknown tag "simulated_actuated_joint" in /robot[@name='pr2']/transmission[@name='torso_lift_trans']
Unknown attribute "type" in /robot[@name='pr2']/link[@name='wide_stereo_optical_frame']
Unknown attribute "type" in /robot[@name='pr2']/link[@name='narrow_stereo_optical_frame']
Unknown attribute "type" in /robot[@name='pr2']/link[@name='laser_tilt_link']
Unknown tag "compensator" in /robot[@name='pr2']/transmission[@name='r_shoulder_pan_trans']
Unknown tag "compensator" in /robot[@name='pr2']/transmission[@name='r_shoulder_lift_trans']
Traceback (most recent call last):
  File "/home/applications/ishida_ws/src/calibration/calibration_launch/scripts/capture_exec.py", line 321, in <module>
    executive = CaptureExecutive(config_dir, system, robot_description)
  File "/home/applications/ishida_ws/src/calibration/calibration_launch/scripts/capture_exec.py", line 73, in __init__
    links = list(URDF().parse(robot_desc).link_map.keys())
  File "/opt/ros/noetic/lib/python3/dist-packages/urdf_parser_py/xml_reflection/core.py", line 669, in parse
    self.read_xml(node, path)
  File "/opt/ros/noetic/lib/python3/dist-packages/urdf_parser_py/xml_reflection/core.py", line 598, in read_xml
    self.XML_REFL.set_from_xml(self, node, path)
  File "/opt/ros/noetic/lib/python3/dist-packages/urdf_parser_py/xml_reflection/core.py", line 513, in set_from_xml
    element.add_from_xml(obj, child, element_path)
  File "/opt/ros/noetic/lib/python3/dist-packages/urdf_parser_py/xml_reflection/core.py", line 390, in add_from_xml
    value = self.value_type.from_xml(node, path)
  File "/opt/ros/noetic/lib/python3/dist-packages/urdf_parser_py/xml_reflection/core.py", line 283, in from_xml
    raise ParseError(Exception(out), path)
urdf_parser_py.xml_reflection.core.ParseError: ParseError in /robot[@name='pr2']/transmission[@name='r_wrist_trans']:
Could not perform duck-typed parsing.
Value Type: <class 'urdf_parser_py.urdf.Transmission'>
Exception: ParseError in /robot[@name='pr2']/transmission[@name='r_wrist_trans']:
Required element not set in XML: type

[calibration_exec-59] process has died [pid 1628407, exit code 1, cmd /home/applications/ishida_ws/src/calibration/calibration_launch/scripts/capture_exec.py /home/applications/ishida_ws/src/pr2_calibration/pr2_calibration_launch/capture_data/samples_pr2_beta /home/applications/ishida_ws/src/pr2_calibration/pr2_calibration_launch/capture_data/hardware_config /home/applications/ishida_ws/src/pr2_calibration/pr2_calibration_launch/estimate_params/config_pr2_beta/system.yaml kinect_head/camera_info:=kinect_head/rgb/camera_info kinect_head/image_rect:=kinect_head/rgb/image_mono kinect_head/image:=kinect_head/rgb/image_mono kinect_head/features:=kinect_head/rgb/features kinect_torso/camera_info:=kinect_torso/rgb/camera_info kinect_torso/image_rect:=kinect_torso/rgb/image_mono kinect_torso/image:=kinect_torso/rgb/image_mono kinect_torso/features:=kinect_torso/rgb/features prosilica_rect/camera_info:=prosilica/camera_info prosilica_rect/image_rect:=prosilica/image_rect prosilica_rect/image:=prosilica/image_raw prosilica_rect/features:=prosilica/features narrow_left_rect/camera_info:=narrow_stereo/left/camera_info narrow_left_rect/image_rect:=narrow_stereo/left/image_rect narrow_left_rect/image:=narrow_stereo/left/image_raw narrow_left_rect/features:=narrow_stereo/left/features narrow_right_rect/camera_info:=narrow_stereo/right/camera_info narrow_right_rect/image_rect:=narrow_stereo/right/image_rect narrow_right_rect/image:=narrow_stereo/right/image_raw narrow_right_rect/features:=narrow_stereo/right/features wide_left_rect/camera_info:=wide_stereo/left/camera_info wide_left_rect/image_rect:=wide_stereo/left/image_rect wide_left_rect/image:=wide_stereo/left/image_raw wide_left_rect/features:=wide_stereo/left/features wide_right_rect/camera_info:=wide_stereo/right/camera_info wide_right_rect/image_rect:=wide_stereo/right/image_rect wide_right_rect/image:=wide_stereo/right/image_raw wide_right_rect/features:=wide_stereo/right/features forearm_right_rect/camera_info:=r_forearm_cam/camera_info forearm_right_rect/image_rect:=r_forearm_cam/image_rect forearm_right_rect/image:=r_forearm_cam/image_raw forearm_right_rect/features:=r_forearm_cam/features forearm_left_rect/camera_info:=l_forearm_cam/camera_info forearm_left_rect/image_rect:=l_forearm_cam/image_rect forearm_left_rect/image:=l_forearm_cam/image_raw forearm_left_rect/features:=l_forearm_cam/features tilt_laser/image_features:=tilt_laser/laser_checkerboard tilt_laser/laser_interval:=tilt_laser/laser_checkerboard_interval tilt_laser/snapshot:=tilt_laser/dense_laser_snapshot tilt_laser/laser_image:=tilt_laser/cb_image tilt_laser/joint_features:=tilt_laser/joint_state_features __name:=calibration_exec __log:=/home/applications/.ros/log/20231119-043725_e668f992-8649-11ee-9477-bfd4e0e70484/calibration_exec-59.log].
log file: /home/applications/.ros/log/20231119-043725_e668f992-8649-11ee-9477-bfd4e0e70484/calibration_exec-59*.log
```

**Comment by HiroIshida** [comment]
これでひとまず動く
export ROS_ENV_LOADER=~/ros/noetic/devel/env.sh
https://github.com/HiroIshida/calibration/tree/noetic_3x_compat/calibration_launch をソースビルド
roslaunch pr2_calibration_launch capture_data.launch

**Comment by HiroIshida** [comment]
次はこんなエラーでてきた
```
Press <enter> to continue, type N to exit this step
>>>
On Far sample [/home/applications/ishida_ws/src/pr2_calibration/pr2_calibration_launch/capture_data/samples_pr2_beta/0_far/far_0000.yaml]
[ERROR] [1700471532.838877] [/calibration_exec:rosout]: Got a transition callback on a goal handle that we're not tracking
[ERROR] [1700471532.842451] [/calibration_exec:rosout]: Got a transition callback on a goal handle that we're not tracking
Enabling:
 + narrow_left_rect
 + narrow_right_rect
 + wide_left_rect
 + wide_right_rect
 + prosilica_rect
 + kinect_head
 + head_chain
 + tilt_laser
Disabling:
 - forearm_left_rect
 - forearm_right_rect
 - right_arm_chain
 - left_arm_chain

Collecting sensor data..
Stopping sensor streams..

Didn't get good data from prosilica_rect, tilt_laser
--------------- Failed To Capture a Far Sample -----------------
Succeeded on 0 Far samples
```

**Comment by HiroIshida** [comment]
Note: The texture projector must be off for data capture to work!と書いたので次を走らせる。でもいみなかった。
roslaunch pr2_camera_synchronizer projector_off.launch

**Comment by HiroIshida** [comment]
"Didn't get good data..." でtilt laserがでてる. なぜだか調べるために、calibration_launchの"capture_exex.py"を読んでみると、calibration_msgs.msg.IntervalStatusが出している値
interval_status.yield_rates[i] が0.0だとbad sensor扱いになっている.

このinterval_intersectionというノードがaggregateして出しているっぽい.
```
applications@pr1040:~/ishida_ws/src/calibration/calibration_launch$ rosnode info /interval_intersection
--------------------------------------------------------------------------------
Node [/interval_intersection]
Publications: 
 * /intersected_interval [calibration_msgs/Interval]
 * /intersected_interval_status [calibration_msgs/IntervalStatus]
 * /interval_intersection_config/feedback [interval_intersection/ConfigActionFeedback]
 * /interval_intersection_config/result [interval_intersection/ConfigActionResult]
 * /interval_intersection_config/status [actionlib_msgs/GoalStatusArray]
 * /rosout [rosgraph_msgs/Log]

Subscriptions: 
 * /head_chain/settled_interval [calibration_msgs/Interval]
 * /interval_intersection_config/cancel [actionlib_msgs/GoalID]
 * /interval_intersection_config/goal [interval_intersection/ConfigActionGoal]
 * /kinect_head/rgb/settled_interval [calibration_msgs/Interval]
 * /narrow_stereo/left/settled_interval [calibration_msgs/Interval]
 * /narrow_stereo/right/settled_interval [calibration_msgs/Interval]
 * /tilt_laser/settled_interval [calibration_msgs/Interval]
 * /wide_stereo/left/settled_interval [calibration_msgs/Interval]
 * /wide_stereo/right/settled_interval [calibration_msgs/Interval]
```
```
applications@pr1040:~/ishida_ws/src/calibration/calibration_launch$ rostopic info /tilt_laser/settled_interval
Type: calibration_msgs/Interval

Publishers: 
 * /tilt_laser/laser_settler (http://pr1040:41565/)

Subscribers: 
 * /interval_intersection (http://pr1040:36125/)
```

```
applications@pr1040:~/ishida_ws/src/calibration/calibration_launch$ rostopic echo /tilt_laser/settled_interval
start: 
  secs: 1700560486
  nsecs: 373367889
end: 
  secs: 1700560486
  nsecs: 373367889
---
start: 
  secs: 1700560502
  nsecs: 391089889
end: 
  secs: 1700560502
  nsecs: 391089889
---
```
```
^Capplications@pr1040:~/ishida_ws/src/calibration/calibration_launch$ rostopic echo /narrow_stereo/left/settled_interval
start: 
  secs: 1700560558
  nsecs: 861734032
end: 
  secs: 1700560558
  nsecs: 929830770
---
start: 
  secs: 1700560558
  nsecs: 861734032
end: 
  secs: 1700560558
  nsecs: 997638639
---
start: 
  secs: 1700560560
  nsecs: 901726191
end: 
  secs: 1700560560
  nsecs: 901726191
---
```
narrow stereoのほうはそもそもpublishがはやいけど, tiltのほうは遅い

**Comment by HiroIshida** [comment]
https://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration　の指示にしたがって, camera calibrationを行う. calibrateボタンが表示されるまで, pr2の首をぐるぐるまわす. 
calibrationが終わると次のようなデータがterminalに出力される. 
```
[image]

width
640

height
480

[narrow_stereo]

camera matrix
550.472951 0.000000 323.930908
0.000000 556.173740 256.540713
0.000000 0.000000 1.000000

distortion
0.209885 -0.366814 -0.007457 0.005185 0.000000

rectification
1.000000 0.000000 0.000000
0.000000 1.000000 0.000000
0.000000 0.000000 1.000000

projection
566.551758 0.000000 326.405929 0.000000
0.000000 573.821777 253.332520 0.000000
0.000000 0.000000 1.000000 0.000000
```
```
rosrun camera_calibration_parsers convert camera.ini camera.yaml
```
でyamlに変換

**Comment by HiroIshida** [comment]
irのcalibrationを行う. よく落ちる. usb resetする.

```
import subprocess
import os

p = subprocess.Popen("lsusb", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = p.communicate()
lines = stdout.split("\n")
for line in lines:
    print(line)
print("^^^^^^^^^^^^^^^^^^^^")
# ms_line = [l for l in lines if "ASUS" in l][0]
ms_lines = [l for l in lines if "Microsoft" in l]
for ms_line in ms_lines:
    print(ms_line)
    tmp = ms_line.split(' ')
    bus_id, device_id = tmp[1], tmp[3]
    print(bus_id)
    full_path = "/dev/bus/usb/" + bus_id + "/" + device_id.rstrip(":")
    print(full_path)
    print('rosrun openni2_camera usb_reset ' + full_path)
    if os.access(full_path, os.W_OK):
        retcode = subprocess.call('rosrun openni2_camera usb_reset ' + full_path, shell=True)
```

**Comment by HiroIshida** [comment]
```
rosrun camera_calibration cameracalibrator.py image:=/kinect_head/ir/image_raw camera:=/kinect_head/ir --size 5x4 --square 0.0245
```
IR-image, rvizでは見えてるのに, camera_calibrationでは見れない... 
![Screenshot from 2023-12-06 09-19-00](https://github.com/HiroIshida/snippets/assets/38597814/eb517816-44d9-472e-8fc3-e6f4ddabc90e)

**Comment by HiroIshida** [comment]
calibration終わったあと, kinectのcamera infoが出荷時にもどらない... ハードウェアに書き込まれている...
```
[http://pr1040:11311][133.11.216.116] h-ishida@azarashi:~/tmp/camera_calibration$ rosservice info /kinect_head/rgb/set_camera_info
Node: /kinect_head/kinect_head_nodelet_manager
URI: rosrpc://pr1040:54671
Type: sensor_msgs/SetCameraInfo
Args: camera_info
```

**Comment by HiroIshida** [comment]
Dec  5 17:10:25 pr1040 jsk-pr2-startup[70617]: #033[33m[ WARN] [1701763825.564456698] [/kinect_head/kinect_head_nodelet_manager:ros.camera_info_manager]: Camera calibration file /home/applications/.ros/camera_info/rgb_A00362913844045A.yaml not found.#033[0m
Dec  5 17:10:25 pr1040 jsk-pr2-startup[70617]: #033[33m[ WARN] [1701763825.564504515] [/kinect_head/kinect_head_nodelet_manager:ros.openni_camera./kinect_head/driver]: Using default parameters for RGB camera calibration.#033[0m
Dec  5 17:10:25 pr1040 jsk-pr2-startup[70617]: #033[33m[ WARN] [1701763825.564532073] [/kinect_head/kinect_head_nodelet_manager:ros.camera_info_manager]: Camera calibration file /home/applications/.ros/camera_info/depth_A00362913844045A.yaml not found.#033[0m

**Comment by HiroIshida** [comment]
キャリブレーション後 (IR param1)
![image](https://github.com/HiroIshida/snippets/assets/38597814/83679a5b-bb32-4609-ae70-c86a9f626246)

![image](https://github.com/HiroIshida/snippets/assets/38597814/fb3e5916-56e7-4ff4-89bc-10da73198edc)

![image](https://github.com/HiroIshida/snippets/assets/38597814/6f9c4d61-2452-42d3-96e3-2baeb767d055)

![image](https://github.com/HiroIshida/snippets/assets/38597814/c1a1150a-5148-4530-8547-30dc97322677)

**Comment by HiroIshida** [comment]
キャリブレーション前
![image](https://github.com/HiroIshida/snippets/assets/38597814/12779f64-f32a-4812-a28a-53cb8c599db5)
![image](https://github.com/HiroIshida/snippets/assets/38597814/f549c39b-07c2-4546-a058-bd22b388de7f)
![image](https://github.com/HiroIshida/snippets/assets/38597814/fbdacafc-d755-4a11-a5f4-5730014fd4f6)
![image](https://github.com/HiroIshida/snippets/assets/38597814/c63ef9f4-6531-4292-9a8f-e674e433703c)
